-- DOMINIUM web auth schema for Supabase.
-- Run once in Supabase SQL Editor before DOMINIUM_AUTH_BACKEND=supabase.
-- The browser never talks to these tables directly; only the server secret does.

create table if not exists public.dominium_profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  role text not null check (role in ('admin','controller','viewer')),
  status text not null check (status in ('pending','active','disabled','rejected')),
  contact_email text,                                           -- optional metadata, never used as Supabase auth credential
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by bigint references public.dominium_profiles(id),
  rejected_at timestamptz,
  rejected_by bigint references public.dominium_profiles(id),
  rejection_reason text,
  last_login_at timestamptz,
  failed_attempts integer not null default 0,
  locked_until timestamptz,
  constraint dominium_username_lowercase check (username = lower(username)),
  constraint dominium_username_shape check (username ~ '^[a-z0-9][a-z0-9._-]{2,47}$')
);

create index if not exists idx_dominium_profiles_status
  on public.dominium_profiles(status);

create table if not exists public.dominium_sessions (
  token_hash text primary key,
  user_id bigint not null references public.dominium_profiles(id) on delete cascade,
  csrf_hash text not null,
  csrf_token text not null,
  created_at timestamptz not null,
  last_seen_at timestamptz not null,
  expires_at timestamptz not null,
  absolute_expires_at timestamptz not null,
  user_agent_hash text not null default ''
);

create index if not exists idx_dominium_sessions_user
  on public.dominium_sessions(user_id);
create index if not exists idx_dominium_sessions_expiry
  on public.dominium_sessions(absolute_expires_at);

create table if not exists public.dominium_imperium_identities (
  user_id bigint not null references public.dominium_profiles(id) on delete cascade,
  profile_key text not null,
  imperium_username text not null,
  controller_id bigint not null,
  verified_at timestamptz not null,
  verified_by bigint references public.dominium_profiles(id),
  primary key (user_id, profile_key)
);

create index if not exists idx_dominium_imperium_controller
  on public.dominium_imperium_identities(profile_key, controller_id);

create table if not exists public.dominium_operator_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id bigint references public.dominium_profiles(id) on delete set null,
  username text not null,
  action text not null,
  result text not null,
  request_id text not null default '',
  channel text not null default 'dominium',
  target text not null default '',
  technician text not null default '',
  external_actor text not null default '',
  metadata_json text not null default '{}'
);

create index if not exists idx_dominium_audit_created
  on public.dominium_operator_audit(created_at desc);
create index if not exists idx_dominium_audit_user
  on public.dominium_operator_audit(user_id, created_at desc);

-- Defense in depth: no anon/authenticated browser access to server-owned auth tables.
alter table public.dominium_profiles enable row level security;
alter table public.dominium_sessions enable row level security;
alter table public.dominium_imperium_identities enable row level security;
alter table public.dominium_operator_audit enable row level security;

revoke all on table public.dominium_profiles from anon, authenticated;
revoke all on table public.dominium_sessions from anon, authenticated;
revoke all on table public.dominium_imperium_identities from anon, authenticated;
revoke all on table public.dominium_operator_audit from anon, authenticated;

grant all on table public.dominium_profiles to service_role;
grant all on table public.dominium_sessions to service_role;
grant all on table public.dominium_imperium_identities to service_role;
grant all on table public.dominium_operator_audit to service_role;
grant usage, select on all sequences in schema public to service_role;
