'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {buildPlan,createReviewStore}=require('../core');
const now=Date.parse('2026-10-10T17:00:00Z');
const atlas={enderecaveis_negrito:['ABC123456789'],serial_baixavel:'ABC123456789',modelo_equipamento:'DECODER',historico:[{numero_contrato:'3902235'}]};
const check=extra=>({ok:true,confirmed:true,searched:true,source:'imperium_detail',profile_key:'natal',contract:'3902235',checked_at:new Date(now).toISOString(),orders:[{num_os:'12345',id_os:1,contract:'3902235',installer_id:42,installer_name:'Técnico',status:'EM CAMPO'}],...extra});
const batch=extra=>({profile:'natal',contract:'3902235',sender:'wa@lid',technician:{name:'Técnico',imperium_id:'42'},atlas:[atlas],require_imperium_verification:true,imperium:check(),...extra});
const toa=extra=>({contract:'3902235',activity_status:'started',materials_complete:false,tasks:[{os_number:'12345',close_code:'430'}],removed_equipments:[],...extra});
test('430 Atlas com OS do remetente independe conclusão e login TOA',()=>{const p=buildPlan(batch(),toa(),now);assert.deepEqual(p.blockers,[]);assert.equal(p.operations[0].os,'12345');assert.equal(p.operations[0].outgoing[0].source,'ATLAS');assert.equal(p.executed,false)});
test('Imperium ausente, desatualizado, outra cidade/contrato/técnico/OS bloqueiam',()=>{for(const evidence of [null,check({checked_at:new Date(now-300001).toISOString()}),check({profile_key:'recife'}),check({contract:'1234567'}),check({orders:[{num_os:'12345',id_os:1,contract:'3902235',installer_id:99}]}),check({orders:[]})])assert.ok(buildPlan(batch({imperium:evidence}),toa(),now).blockers.length)});
test('430 TOA sem serial Atlas ou com material/entrada segue bloqueada',()=>{assert.ok(buildPlan(batch({atlas:[]}),toa({removed_equipments:[{serial:'ABC123456789',equipment_type:'DECODER'}]}),now).blockers.length);for(const extra of [{materials:[{quantity:1}]},{installed_equipments:[{serial:'INS123456789',equipment_type:'DECODER'}]}])assert.ok(buildPlan(batch(),toa(extra),now).blockers.length)});
test('409 mantém conclusão, materiais e movimentos TOA sem converter código',()=>{const p=buildPlan(batch(),toa({tasks:[{os_number:'12345',close_code:'409'}],installed_equipments:[{serial:'INS123456789',equipment_type:'DECODER'}]}),now);assert.ok(p.blockers.some(x=>x.includes('concluída')));assert.ok(p.blockers.some(x=>x.includes('materiais')));assert.equal(p.operations[0].code,'409')});
test('sem TOA não cria OS duplicada quando Imperium encontra OS aberta',()=>{assert.ok(buildPlan(batch({requested_code:'430'}),null,now).blockers.some(x=>x.includes('seleção')));const p=buildPlan(batch({imperium:check({source:'open_orders_no_match',orders:[]})}),null,now);assert.deepEqual(p.blockers,[]);assert.equal(p.operations[0].create_os,true)});
test('aprovação rejeita evidência envelhecida e mudança do recurso invalida vínculo',()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'desc-order-'));try{let time=now;const s=createReviewStore({directory,groups:{g:{profile:'natal'}},technicians:{wa:{name:'T',imperium_id:'42'}},now:()=>time,windowMs:0,requireImperiumVerification:true});const b=s.ingest({id:'msg',group:'g',sender:'wa',contract:'3902235',atlas:[atlas]});const p=s.prepare(b.id,toa(),[],check());assert.equal(p.state,'review');time+=300001;assert.throws(()=>s.decide(b.id,'approve',p.revision,'Dalton'),/Imperium/);time=now;s.updateTechnician('wa',{name:'T',imperium_id:'99'});assert.equal(s.get(b.id).state,'blocked')}finally{fs.rmSync(directory,{recursive:true,force:true})}});
test('código pedido divergente nunca permite converter409 em430',()=>{const p=buildPlan(batch({requested_code:'409'}),toa(),now);assert.ok(p.blockers.some(x=>x.includes('Código solicitado')))});
test('resposta privada malformada bloqueia sem travar lote processing',()=>{for(const orders of [[null],[42],[{num_os:'12345',id_os:1,contract:'3902235',installer_id:42,status:'CONCLUÍDA'}]])assert.ok(buildPlan(batch({imperium:check({orders})}),toa(),now).blockers.length)});
test('recurso zero ou número fora precisão bloqueia criação',()=>{for(const id of ['0','9007199254740993','abc'])assert.ok(buildPlan(batch({technician:{imperium_id:id},imperium:check({source:'open_orders_no_match',orders:[]})}),null,now).blockers.length)});

test('objetos JSON inválidos nunca causam coerção no verificador',()=>{for(const evidence of [check({checked_at:{toString:null}}),check({orders:[{num_os:{toString:null},id_os:1,installer_id:42}]}),check({orders:[{num_os:'12345',id_os:1,installer_id:{toString:null}}]})])assert.ok(buildPlan(batch({imperium:evidence}),toa(),now).blockers.length)});
